import { Rubik } from "next/font/google";
import "./globals.css";
import "animate.css";
import GoogleAnalytics from "./analytics";

const rubik = Rubik({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Jajan Panglima",
  description: "Generated by syafar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://raw.githubusercontent.com/Syafar44/assets/main/assets/image/LOGO%20JAJAN%20Panglima-01.png"
          type="image/png"
          sizes="16x16"
        />
      </head>
      <body className={`${rubik.className}`}>
        <GoogleAnalytics />
        {children}
      </body>
    </html>
  );
}
